import random

# List of 100 two-phrase Indonesian names and emails
indonesian_names_and_emails = [
    ("Ahmad Fauzi", "ahmad.fauzi@email.com"),
    ("Budi Santoso", "budi.santoso@email.com"),
    ("Citra Dewi", "citra.dewi@email.com"),
    ("Dian Pratiwi", "dian.pratiwi@email.com"),
    ("Eko Wijaya", "eko.wijaya@email.com"),
    ("Fitriani Sari", "fitriani.sari@email.com"),
    ("Guntur Setiawan", "guntur.setiawan@email.com"),
    ("Hana Putri", "hana.putri@email.com"),
    ("Indra Kusuma", "indra.kusuma@email.com"),
    ("Joko Prabowo", "joko.prabowo@email.com"),
    ("Kartika Wulandari", "kartika.wulandari@email.com"),
    ("Luki Hermawan", "luki.hermawan@email.com"),
    ("Maya Indah", "maya.indah@email.com"),
    ("Nurul Hasanah", "nurul.hasanah@email.com"),
    ("Oki Ramadhan", "oki.ramadhan@email.com"),
    ("Putri Ayu", "putri.ayu@email.com"),
    ("Rudi Hartono", "rudi.hartono@email.com"),
    ("Sari Utami", "sari.utami@email.com"),
    ("Taufik Hidayat", "taufik.hidayat@email.com"),
    ("Umi Khairiah", "umi.khairiah@email.com"),
    ("Vina Amelia", "vina.amelia@email.com"),
    ("Wahyu Nugroho", "wahyu.nugroho@email.com"),
    ("Yuni Astuti", "yuni.astuti@email.com"),
    ("Zainal Abidin", "zainal.abidin@email.com"),
    ("Agus Supriyadi", "agus.supriyadi@email.com"),
    ("Bella Puspita", "bella.puspita@email.com"),
    ("Candra Wijaya", "candra.wijaya@email.com"),
    ("Dewi Lestari", "dewi.lestari@email.com"),
    ("Eka Prasetya", "eka.prasetya@email.com"),
    ("Fajar Nugraha", "fajar.nugraha@email.com"),
    ("Gita Permata", "gita.permata@email.com"),
    ("Hendra Saputra", "hendra.saputra@email.com"),
    ("Intan Permatasari", "intan.permatasari@email.com"),
    ("Jaya Kusuma", "jaya.kusuma@email.com"),
    ("Kurniawan Adi", "kurniawan.adi@email.com"),
    ("Lina Marlina", "lina.marlina@email.com"),
    ("Muhammad Ali", "muhammad.ali@email.com"),
    ("Nadia Fitri", "nadia.fitri@email.com"),
    ("Oscar Wijaya", "oscar.wijaya@email.com"),
    ("Puspita Sari", "puspita.sari@email.com"),
    ("Rizky Pratama", "rizky.pratama@email.com"),
    ("Siska Dewi", "siska.dewi@email.com"),
    ("Teguh Santoso", "teguh.santoso@email.com"),
    ("Ulfa Rahma", "ulfa.rahma@email.com"),
    ("Vito Pratama", "vito.pratama@email.com"),
    ("Wulan Sari", "wulan.sari@email.com"),
    ("Yoga Permana", "yoga.permana@email.com"),
    ("Zahra Fitriani", "zahra.fitriani@email.com"),
    ("Adi Nugroho", "adi.nugroho@email.com"),
    ("Bunga Citra", "bunga.citra@email.com"),
    ("Cahya Putra", "cahya.putra@email.com"),
    ("Dinda Permatasari", "dinda.permatasari@email.com"),
    ("Eko Prasetyo", "eko.prasetyo@email.com"),
    ("Fani Amelia", "fani.amelia@email.com"),
    ("Gede Wijaya", "gede.wijaya@email.com"),
    ("Hesti Purnama", "hesti.purnama@email.com"),
    ("Irfan Setiawan", "irfan.setiawan@email.com"),
    ("Jasmine Putri", "jasmine.putri@email.com"),
    ("Kiki Amalia", "kiki.amalia@email.com"),
    ("Larasati Dewi", "larasati.dewi@email.com"),
    ("Mega Puspita", "mega.puspita@email.com"),
    ("Nanda Pratama", "nanda.pratama@email.com"),
    ("Oki Saputra", "oki.saputra@email.com"),
    ("Putra Wijaya", "putra.wijaya@email.com"),
    ("Rina Marlina", "rina.marlina@email.com"),
    ("Surya Nugraha", "surya.nugraha@email.com"),
    ("Tasya Fitri", "tasya.fitri@email.com"),
    ("Umar Said", "umar.said@email.com"),
    ("Vina Puspita", "vina.puspita@email.com"),
    ("Wahid Hidayat", "wahid.hidayat@email.com"),
    ("Yoga Saputra", "yoga.saputra@email.com"),
    ("Zaki Ramadhan", "zaki.ramadhan@email.com"),
    ("Aisyah Nur", "aisyah.nur@email.com"),
    ("Bagus Setiawan", "bagus.setiawan@email.com"),
    ("Cinta Dewi", "cinta.dewi@email.com"),
    ("Dodi Pratama", "dodi.pratama@email.com"),
    ("Eva Rahmawati", "eva.rahmawati@email.com"),
    ("Firman Syah", "firman.syah@email.com"),
    ("Gita Puspita", "gita.puspita@email.com"),
    ("Hadi Nugroho", "hadi.nugroho@email.com"),
    ("Indah Permata", "indah.permata@email.com"),
    ("Joko Susilo", "joko.susilo@email.com"),
    ("Kartika Sari", "kartika.sari@email.com"),
    ("Luki Setiawan", "luki.setiawan@email.com"),
    ("Mira Puspita", "mira.puspita@email.com"),
    ("Nina Rahmawati", "nina.rahmawati@email.com"),
    ("Oki Wijaya", "oki.wijaya@email.com"),
    ("Putri Lestari", "putri.lestari@email.com"),
    ("Rizki Pratama", "rizki.pratama@email.com"),
    ("Sari Dewi", "sari.dewi@email.com"),
    ("Toni Setiawan", "toni.setiawan@email.com"),
    ("Umi Kalsum", "umi.kalsum@email.com"),
    ("Vino Pratama", "vino.pratama@email.com"),
    ("Winda Sari", "winda.sari@email.com"),
    ("Yoga Wijaya", "yoga.wijaya@email.com"),
    ("Zahra Puspita", "zahra.puspita@email.com"),
]

def get_random_name():
    """
    Returns a random Indonesian name and email from the list.
    """
    return random.choice(indonesian_names_and_emails)

def generate_phone_number():
    """Generate a random 11-digit Indonesian phone number with prefix +628"""
    number = f"+628{random.randint(10000000, 99999999)}"
    return number

# Example usage
if __name__ == "__main__":
    name, email = get_random_name()
    print(f"Name: {name}, Email: {email}")